theme: jekyll-theme-cayman
title: "CS294-238/CS194-238 Zero Knowledge Proofs"
description: Spring 2023
show_downloads: false
github:
  is_project_page: false
plugins:
  - jekyll-redirect-from
baseurl: /zkp-course
